stages:
  - build
  - test

image: python:3.8-slim-buster

before_script:
  - pip install -r requirements.txt


build:
  stage: build
  script:
    - pip install --upgrade pip
    - python -m build
    

test:
  stage: test
  script:
    - pip install -e .
    - pytest --cov=src/treevolution
    - sphinx-build -b html docs/source/ docs/build
