stages:
  - build
  - test

image: python:3.8-slim-buster

before_script:
  script:
    - pip install -r requirements.txt
    

build:
  stage: build
  script:
    - pip install --upgrade pip
    - python -m build
    - pip install -e .

test:
  stage: test
  script:
    - pytest
    - pytest --cov=src/treevolution
